trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AWSShellScript@1
  displayName: 'Test AWS OIDC Connection'
  inputs:
    awsCredentials: '<YOUR_SERVICE_CONNECTION_NAME>'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      echo "Testing AWS OIDC authentication..."
      aws sts get-caller-identity
      echo "Connection successful!"
